export const FETCH_HANGER_DATA_REQUEST = 'FETCH_HANGER_DATA_REQUEST';

export const FETCH_HANGER_DATA_SUCCESS = 'FETCH_HANGER_DATA_SUCCESS';

export const FETCH_HANGER_DATA_FAIL = 'FETCH_HANGER_DATA_FAIL';

export const DELETE_HANGER_ROW_SUCCESS = 'DELETE_HANGER_ROW_SUCCESS';

export const DELETE_HANGER_ROW_REQUEST = 'DELETE_HANGER_ROW_REQUEST';

export const DELETE_HANGER_ROW_FAIL = 'DELETE_HANGER_ROW_FAIL';

export const ADD_HANGER_ROW_SUCCESS = 'ADD_HANGER_ROW_SUCCESS';

export const ADD_HANGER_ROW_REQUEST = 'ADD_HANGER_ROW_REQUEST';

export const ADD_HANGER_ROW_FAIL = 'ADD_HANGER_ROW_FAIL';