export const FETCH_HANGER_DATA_REQUEST = 'FETCH_HANGER_DATA_REQUEST';

export const FETCH_HANGER_DATA_SUCCESS = 'FETCH_HANGER_DATA_SUCCESS';

export const FETCH_HANGER_DATA_FAIL = 'FETCH_HANGER_DATA_FAIL';